### ISSUE TITLE
Next batch of todo's

### ISSUE THREAD

**Issue by garfbradaz** [garfbradaz/clarizen.js#1]
- [ ] Add the **createAndRetrieve** method to clarizen.js:

[Clarizen API Documentation](https://api.clarizen.com/V2.0/services/data/CreateAndRetrieve)
- [ ] Add the **bulk** method to clarizen.js:

[Clarizen API Documentation](https://api.clarizen.com/V2.0/services/bulk/Execute)
- [ ] Add required field asterixs tp css/html examples,
